spring:
  profiles:
    active: local
    group:
      prod:
        - data
        - jwt
        - cookie
        - secret
        - server
        - oauth2
      dev:
        - data
        - jwt
        - cookie
        - secret
        - server
        - docs
        - oauth2
      local:
        - data
        - jwt
        - cookie
        - secret
        - server
        - docs
        - oauth2
      test:
        - testdata
        - jwt
        - cookie
        - secret
        - server
        - docs
        - oauth2