spring:
  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
  data:
    redis:
      host: ${properties.data.redis.host}
      port: ${properties.data.redis.port}
      password: ${properties.data.redis.password}