spring:
  profiles:
    active: local
    group:
      prod:
        - rdb
        - redis
        - jwt
        - cookie
        - secret
        - server
        - oauth2
        - feign
        - storage
      dev:
        - rdb
        - redis
        - jwt
        - cookie
        - secret
        - server
        - docs
        - oauth2
        - feign
        - storage
      local:
        - rdb
        - redis
        - jwt
        - cookie
        - secret
        - server
        - docs
        - oauth2
        - feign
        - storage