spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${properties.oauth2.google.client-id}
            client-secret: ${properties.oauth2.google.client-secret}
            scope:
              - profile
              - email
            redirect-uri: ${properties.oauth2.google.redirect-uri}
          kakao:
            client-id: ${properties.oauth2.kakao.client-id}
            client-secret: ${properties.oauth2.kakao.client-secret}
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
            redirect-uri: ${properties.oauth2.kakao.redirect-uri}
          naver:
            client-id: ${properties.oauth2.naver.client-id}
            client-secret: ${properties.oauth2.naver.client-secret}
            authorization-grant-type: authorization_code
            scope: nickname, profile_image, email, mobile
            client-name: Naver
            redirect-uri: ${properties.oauth2.naver.redirect-uri}
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
      cookieName: ${properties.oauth2.cookie-name}
      redirectUriSuccess: ${properties.oauth2.redirectUriSuccess}
      redirectUriSignUp: ${properties.oauth2.redirectUriSignUp}
      redirectUriFailure: ${properties.oauth2.redirectUriFailure}
      cookieExpireSeconds: ${properties.oauth2.cookie-expire-seconds}