spring:
  config:
    activate:
      on-profile: "prod"

custom:
  sms:
    verification:
      code-length: 6
      limit-per-day: 3
    send-limit:
      sign-up: 3
---
spring:
  config:
    activate:
      on-profile: "dev"

custom:
  sms:
    verification:
      code-length: 6
      limit-per-day: 3
    send-limit:
      sign-up: 100
---
spring:
  config:
    activate:
      on-profile: "local"

custom:
  sms:
    verification:
      code-length: 6
      limit-per-day: 3
    send-limit:
      sign-up: 3