version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: my_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pawpaw1234
      MYSQL_DATABASE: pawpaw
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: my_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql_data:
  redis_data:
