version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: my_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pawpaw1234
      MYSQL_DATABASE: pawpaw
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    command: --ngram_token_size=1

  redis:
    image: redis:latest
    container_name: my_redis
    restart: always
    ports:
      - "6379:6379"

  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

volumes:
  mysql_data:
  redis_data:
